name: Docs

on:
  # Publish docs weekly
  schedule:
    - cron:  '0 9 * * 1'
  workflow_dispatch:

jobs:
  documentation:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Python3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: install Python Dependencies
        run: pip3 install nbconvert==5.6.1 mkdocs mkdocs-exclude mknotebooks==0.4.1 mkdocs-material jupyter Pygments Markdown==3.2.2
      - name: Install IJava kernel
        run: |
          git clone https://github.com/frankfliu/IJava.git
          cd IJava/
          ./gradlew installKernel
      - name: clone DJL repo to access the DJL parent dir
        run: git clone https://github.com/awslabs/djl djl_tmp
      - name: add mybinder link
        run: |
          cd djl_tmp
          python3 tools/scripts/add_online_runner.py
      - name: run Notebooks
        run: |
          cd djl_tmp/jupyter
          bash test_notebook.sh
      - name: clone demos
        run: |
          cd djl_tmp/docs
          git clone https://github.com/aws-samples/djl-demo.git demos
      - name: build docs
        run: |
          cd djl_tmp/docs
          mkdocs build --site-dir ../../site
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Copy files to S3 with the AWS CLI
        run: |
          aws s3 sync site s3://djl-ai/documentation/nightly --delete
          aws cloudfront create-invalidation --distribution-id E733IIDCG0G5U --paths "/*"
