name: Nightly Publish

on:
  schedule:
    - cron:  '0 10 * * *'
  workflow_dispatch:
    inputs:
        mode:
          description: 'staging/snapshot, default is snapshot'
          required: true
          default: 'snapshot'

jobs:
  build:
    if: github.repository == 'awslabs/djl'
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [macos-latest, ubuntu-18.04]

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Enable gradle cache: https://github.com/actions/cache/blob/master/examples.md#java---gradle
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: check disk space
        run: df -h
      - name: Build with Gradle
        run: ./gradlew -Dnightly=true build jRR
      - name: API test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: api
          path: api/build/reports
      - name: basicdataset test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: basicdataset
          path: basicdataset/build/reports
      - name: examples test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: examples
          path: examples/build/reports
      - name: integration test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: integration
          path: integration/build/reports
      - name: model-zoo test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: model-zoo
          path: model-zoo/build/reports
      - name: mxnet-engine test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: mxnet-engine
          path: mxnet/mxnet-engine/build/reports
      - name: mxnet-model-zoo test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: mxnet-model-zoo
          path: mxnet/mxnet-model-zoo/build/reports

  test-pytorch:
    if: github.repository == 'awslabs/djl'
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [macos-latest, ubuntu-18.04, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Enable gradle cache: https://github.com/actions/cache/blob/master/examples.md#java---gradle
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Test with Gradle
        run: ./gradlew :integration:test "-Dai.djl.default_engine=PyTorch"

  test-tensorflow:
    if: github.repository == 'awslabs/djl'
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [macos-latest, ubuntu-18.04, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Enable gradle cache: https://github.com/actions/cache/blob/master/examples.md#java---gradle
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Test with Gradle
        run: ./gradlew :integration:test "-Dai.djl.default_engine=TensorFlow"

  publish:
    if: github.repository == 'awslabs/djl'
    runs-on: ubuntu-18.04
    needs: [build, test-pytorch, test-tensorflow]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Enable gradle cache: https://github.com/actions/cache/blob/master/examples.md#java---gradle
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Publish to snapshot repository
        run: |
          ./gradlew publish -P${{ github.event.inputs.mode }}
          cd bom
          ./gradlew publish -P${{ github.event.inputs.mode }}
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingPassword }}
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.ORG_GRADLE_PROJECT_ossrhUsername }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.ORG_GRADLE_PROJECT_ossrhPassword }}
